use_frameworks!

platform :ios, '10.0'

target 'MFMediaPlayer_Example' do
  pod 'MFMediaPlayer', :path => '../'

  target 'MFMediaPlayer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
